### ISSUE TITLE
Feedback from CodersX

### ISSUE THREAD

**Issue by tranthaison1231** [hoangnguyennn/csv-server-rest-api#1]
Project rất tuyệt vời nè, tuy nhiên cần cải thiện thêm những thứ như sau: 
- [x] Cần config thêm file prettier vs eslint. 
- [x] Mình nghĩ bạn nên viết một script để chạy code nè ex: "start": " csv-server ./data --port=3000"

**Comment by hoangnguyennn** [comment]
Đã thêm prettier, eslint config
